repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-byte-order-marker
        exclude: docs/
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
    - id: ruff
      args:
      - --fix
    - id: ruff-format
